---

- name: Run cfg commands on router
  hosts: 192.168.100.1
  gather_facts: false
  connection: local

  tasks:

    - name: Facts
      ios_facts:
        gather_subset: interfaces
        provider: "{{ cli }}"

    - name: Config OSPF
      ios_config:
        src: templates/ospf_facts.j2
        provider: "{{ cli }}"
